
  
# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 2.7
python: 2.7.15

# Install the codecov pip dependency
install:
  - pip install codecov

# Run the unit test
script:
  - run ./tests/account_test_users.py

# Push the results back to codecov
after_success:
  - codecov
